CREATE TABLE [dbo].[SurveyReport] (
    [SurveyReportID]    INT             IDENTITY (1, 1) NOT NULL,
    [RequestID]         INT             NOT NULL,
    [Field]             VARCHAR (20)    NOT NULL,
    [Reservior]         VARCHAR (20)    NOT NULL,
    [RemainingReserve]  DECIMAL (10, 2) NOT NULL,
    [WellName]          VARCHAR (20)    NOT NULL,
    [DateOfSurvey]      DATETIME        NOT NULL,
    [TypeOfSurvey]      VARCHAR (10)    NOT NULL,
    [Oil]               DECIMAL (10, 2) NOT NULL,
    [Water]             DECIMAL (10, 2) NOT NULL,
    [Gas]               DECIMAL (10, 2) NOT NULL,
    [BSW]               DECIMAL (10, 2) NOT NULL,
    [GOR]               DECIMAL (10, 2) NOT NULL,
    [Bean]              DECIMAL (10, 2) NOT NULL,
    [DatumDepth]        DECIMAL (10, 2) NOT NULL,
    [InitialPressure]   DECIMAL (10, 2) NOT NULL,
    [THP]               DECIMAL (10, 2) NOT NULL,
    [CHP]               DECIMAL (10, 2) NOT NULL,
    [FBHP_MP]           DECIMAL (10, 2) NOT NULL,
    [SBHP_MP]           DECIMAL (10, 2) NOT NULL,
    [RP_Datum]          DECIMAL (10, 2) NOT NULL,
    [ProductivityIndex] DECIMAL (10, 2) NOT NULL,
    [Remark]            VARCHAR (MAX)   NULL,
    [CreatedAt]         DATETIME        NOT NULL,
    [DateOfLastSurvey]  DATETIME        NULL,
    CONSTRAINT [PK__SurveyRe__67ED2EA62340B5EF] PRIMARY KEY CLUSTERED ([SurveyReportID] ASC)
);

